### PR TITLE
Update to WP 6.1 with plugin updates

### PR DESCRIPTION
**Pull request by cjyabraham**
[lfeventsci PR instance](https://pr-693-lfeventsci.pantheonsite.io/)
[lfasia PR instance](https://pr-693-lfasiallcci.pantheonsite.io/)

Issues:
1. Gallery images don't have gaps in the right sidebar of [this page](https://pr-693-lfeventsci.pantheonsite.io/about/sponsor/)
2. Spacing change in hero of [this page](https://pr-693-lfeventsci.pantheonsite.io/lf-member-summit/)
3. Spacing after images seems to be consistently smaller

### CODE REVIEW

**Comment by NicoleJudge** [comment]
**Issue:**
- [ ] Icon list block results in "This block has encountered an error and cannot be previewed." In visual editor: no setting options available, and unable to add or edit content.

**Steps to recreate** (any option):

- Create list block, convert it to icon list
- add a new block, select icon list
- from an existing [icon list](https://pr-693-lfeventsci.pantheonsite.io/argocon/program/cfp/#dates-to-remember), click the block to edit it. (list still displays on front end, though errors on editing page)

**Comment by thetwopct** [comment]
@cjyabraham OK those issues are fixed

1. FYI that is not a gallery image, that is just 3 images in a column. Seems the CSS specificity in gutenberg has changed so its picking up a Foundation reset of the margins on the figure tag. I've added in some new css in images.scss to restore the default Gutenberg 1em margin bottom.

2. and 3) Related to the above, although weirdly the markup of the inserted image on 2) is different. The "gallery" images are each in a figure. This image is a div with a figure inside it.

@NicoleJudge Thanks for finding this.

I have changed the way the lists work - I think we will abandon the "Icon List" block, and instead add icon options to the standard List block. So now if you repeat the issue you found with Icon List block, when it shows an error, you can now select **Transform** and then **List**, and the settings for the Icon List block will be transferred to a new List block with icon options.

I made a quick overview video:

https://user-images.githubusercontent.com/10615884/202177994-4458dfd0-6259-460a-b98d-2d598be21371.mp4

A weird quirk of WordPress, if we deactivate the Icon List block the transform stops working 🤷 So for now, we need to keep the Icon List block activated even though it doesn't work... 

I also upgraded WordPress to version 6.1.1. I doubt this will introduce breaking changes, but please do mention any issues you see. Thanks!

**Comment by cjyabraham** [comment]
Thanks James. Can you take a closer look at the use of the new List block. I tried out [some variations on this page](https://pr-693-lfeventsci.pantheonsite.io/open-source-summit-japan/) and made some comments about inconsistencies in rendering.

**Comment by thetwopct** [comment]
@cjyabraham OK give it another look now, I think I've fixed those issues.

**Pull request merged**
