### PR TITLE
Upgrade to WP 6.2 and Conditional Blocks v3.0.2

### PR DESCRIPTION
**Pull request by cjyabraham**
[Dev instance](http://pr-765-lfeventsci.pantheonsite.io/)

Good [intro blog post for Nicole](https://wordpress.org/news/2023/03/dolphy/)

### CODE REVIEW

**Comment by cjyabraham** [comment]
Hi @thetwopct can you take a quick look at this? I can't find anything broken or shifted under the new version of WP. Also Conditional Blocks has released a new version with a fix for what was broken previously. Try and find anything broken and then we'll pass to Nicole for a final test before deploy.

**Comment by cjyabraham** [comment]
Actually there's a bit of weirdness with the Button with Expiry sidebar:
Screen Shot 2023-03-30 at 5 32 02 PM

**Comment by thetwopct** [comment]
- Fixed line breaks
- Added some Conditional Block styling (where it conflicts with group/spacer outlines)

Lets break out the Buttons with Expiry to a new issue, as it doesn't affect its operation, it's just some minor layout glitching

**Review by thetwopct — APPROVED** [review]

**Comment by cjyabraham** [comment]
Waiting for feedback from Nicole.

**Pull request merged**
