### PR TITLE
New footer design for events

### PR DESCRIPTION
**Pull request by thetwopct**
Beginnings of the new footer design for events.

- Horizontal menu should handle any amount of child event pages 
- Design adapts to missing elements (like social icons or navigation)
- Added new param to lfe_get_event_menu() to return a list of child pages without headers

**TODO:** 

- Add meta field for Form Action URL
- Set Form Action conditional for display of newsletter section
- Test form and JS including two forms on one page
- Confirm text editing requirements for newsletter section
- Add meta field for Social Text (hashtags etc), limit to 25 characters (TBC)
- Add Social Text conditional for display of social text

### CODE REVIEW

**Comment by thetwopct** [comment]
@cjyabraham I think this is ready for your review.

- I've added several new meta fields which can override the newsletter text
- Footer does not show if "Splash Page" is activated
- Newsletter does not show if "Form Action" is not set
- Social icons do not show if no links are set
- I've tried to code it so the layout adapts and still looks good if elements do not display
- The nav in column structure doesn't work too well for some events - [too few](https://pr-528-lfeventsci.pantheonsite.io/grpc-conf/), [weird wrapping](https://pr-528-lfeventsci.pantheonsite.io/open-compliance-summit/)
- The different logo sizes, combined with the different amounts of nav items and their lengths, sometimes results in a slightly unbalanced appearance
- The column approach didn't work on mobile, so I've reverted to a list-style display on smaller screens

**Comment by cjyabraham** [comment]
Can you make nav items that wrap to two lines have less line spacing between the two lines?  See "Novel Coronavirus Update" here:
Screen Shot 2020-06-28 at 8 28 11 AM

Is it possible to stop an item from wrapping into a different column?  See "Diversity and Inclusion" [here](https://pr-528-lfeventsci.pantheonsite.io/open-compliance-summit/):
Screen Shot 2020-06-28 at 8 33 42 AM


For the non-column view, would it be worth trying to keep items together on one line?  See "Call for Proposal (CFP)" here which is particularly confusing wrapping to two lines:
Screen Shot 2020-06-28 at 8 29 59 AM

Could you add a space between Japanese and English translations [here](https://pr-528-lfeventsci.pantheonsite.io/open-compliance-summit/).  I believe there might be a `<br>` in the menu text that you could replace with a space:
Screen Shot 2020-06-28 at 8 39 02 AM

I'm not sure what's going on with [this footer](https://pr-528-lfeventsci.pantheonsite.io/lf-member-forum/).  The menu columns start at 2 columns for me, then go to 3, then 2, then 3 when I reduce the browser width.  See [this vid](https://drive.google.com/file/d/1MgwqJ3P-jmCAKjwvD-36R6pXImHmBzs3/view?usp=sharing).  At one point the menu items aren't centered properly:
Screen Shot 2020-06-28 at 8 46 06 AM

**Comment by thetwopct** [comment]
1) + 2) + 4) Done

3) We can stop a line from wrapping - and I have implemented - but when a translation is included in a page title this can send the link off the edge of the page - see [this page](https://pr-528-lfeventsci.pantheonsite.io/lf-member-forum/) on 320px mobile. Can't have one without the other.
5) This may have been related to 2) above, as it appears fixed locally for me. Let me know if it still happens.

6) I don't, but your legal team and the EU might! Have updated.

7) I don't remember that. It means that all social links will always be shown. Can you confirm before this is done as they are all conditional at the moment - if they are always there, code can be simpler.
8) Done. Added tap effect to both buttons.

**Comment by cjyabraham** [comment]
1. I feel the line spacing is too large now between different menu entries.  I liked the spacing you had before.

7. I'll ask Megan.

**Comment by thetwopct** [comment]
1 - Have updated line spacing. 
9 - Updated everything to use the $parent_id variable, forgot about that quirk
10 - Definitely not an exclamation mark, have removed the period

Have also bundled the home page grey menu fix in to this PR

**Comment by cjyabraham** [comment]
7 - Megan has confirmed we should fall back to LF social links when none are provided for the Event.  My sense is that this should be an all-or-nothing deal, so if there is at least one Event-specific social link, then we show just that one.  Only when there are zero Event-specific social links should we show the LF set.  Does that make sense?

**Comment by thetwopct** [comment]
Makes sense. LFE doesn't have a central place for the LF set information (like Global Options on CNCF), should I build it? Otherwise I would hardcode it which I don't like to do but would be the quicker solution.

**Comment by cjyabraham** [comment]
I think hardcoding is fine for now.  Later, if we find they're of use there and elsewhere, we can refactor.

**Comment by cjyabraham** [comment]
11 - The Submit button gets shorter on mobile view.  Can you keep it the same height?
Screen Shot 2020-07-02 at 1 18 15 PM

**Comment by thetwopct** [comment]
OK, ready for review:

- If no social media details are set, pulls in hardcoded LF defaults
- Fixed height of newsletter submit button on mobile

Only thing to confirm is what to do about mobile line-wrapping when an additional language is being used in page titles ([point 3 above](https://github.com/LF-Engineering/lfevents/pull/528#issuecomment-651316115))

**Comment by cjyabraham** [comment]
I've allowed for adding a nowrap span inside the title to keep all english text together, etc, however, this is now causing issues with the title on Safari, in that it doesn't show if wrapped in a span:
Screen Shot 2020-09-24 at 8 33 08 PM

I initially tried filtering out the span from the_title, however, that also filtered it out from the footer as well.  Perhaps it's just a CSS fix that's needed... will have to investigate further and see if there are any other side-effects to having span tags in the title of a page.

**Pull request merged**
