### PR TITLE
Weekly Snaps

### PR DESCRIPTION
**Pull request by cjyabraham**
Based on [this example](https://docs.google.com/document/d/1MB_t22TJ46j734WMzQI0PO_Ejw1SePU9dUupGq1Q9Ac/edit).

[Demo page](https://pr-647-lfeventsci.pantheonsite.io/weekly-snaps/).  Also check out the [button on the sidebar of the homepage](https://pr-647-lfeventsci.pantheonsite.io/).

Still to do:
- [x] @thetwopct to review the style and improve if necessary
- [x] Figure out if we need to remove the individual post pages from site maps etc or should style them so they can be viewed
- [x] Find a way to remove "Archives:" from the `title` meta tag
- [ ] Kristin to provide copy for the description and any other branding info like a snackable

### CODE REVIEW

**Comment by thetwopct** [comment]
I think its good.

1) The singular snaps are visible on the front end and don't display properly as they are loaded inside the event layout
https://pr-647-lfeventsci.pantheonsite.io/weekly-snaps/1

2) We could turn the singular snaps off by adding this to the CPT setup - 'query_var' => false

3) But this doesn't turn off the "View" links in WP Admin, would require more code just for that - https://wordpress.stackexchange.com/a/15325/135299

4) There is no elegant solution, other than styling the singular snaps properly should they be found or needed

5) On the home page, do you think it more appropriate to keep the styling of the section for weekly snaps inline with the other sidebar sections, i.e. something like:

```
<h4 class="medium-margin-bottom">Happening this week</h4>
<p>Our Weekly Snaps summarize news related to Linux Foundation events</p>
<a aria-label="Weekly Snaps" href="/weekly-snaps/">View Weekly Snaps</a>
```

6) I added a block template to the new snaps post, so there is a template there ready to use in your style.

7) If the pictures used are not social sized 1200x630, the layout structure may quickly degrade

**Review by thetwopct — APPROVED** [review]

**Comment by cjyabraham** [comment]
Thanks.  I incorporated some of your suggestions.  Do you think the date styling could be a little more interesting?  Like maybe with a horizontal line below it or something?

**Comment by thetwopct** [comment]
> Do you think the date styling could be a little more interesting? Like maybe with a horizontal line below it or something?

It could be I guess. But I can’t remember a style like that used elsewhere on this site. It looks clean and professional now and I think that’s enough.

**Comment by cjyabraham** [comment]
Closing this as it looks like it's not happening

**Pull request closed without merging**
