### PR TITLE
Small Fixes

### PR DESCRIPTION
**Pull request by thetwopct**
Some small fixes.

- Fix grey screen when closing mobile menu, ref #540
- Added additional spacing to profile photos on mobile/tablet - Issue example - https://take.ms/djqLJ
- Center align countdown on all devices - Issue example - https://take.ms/iI2dm
- Make text centred inside buttons on mobile, add push effect on active - Issue example - https://take.ms/o9FiX
- Use smaller images in front page slider - reduces page load by 200kb
- Dequeued some styles and scripts on front page only
- Move slider script into app.js instead of inline, defer jquery front page only
- Some small accessibility stuff

### CODE REVIEW

**Comment by thetwopct** [comment]
[Before](https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fevents.linuxfoundation.org)
[After](https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fpr-553-lfeventsci.pantheonsite.io%2F)

**Comment by thetwopct** [comment]
I noticed that the Community Events were setup to generate their own pages, [which are unstyled](https://events.linuxfoundation.org/community/paris/), and [being indexed by Google](https://www.google.com/search?client=safari&rls=en&sxsrf=ALeKk016hJWpWOwRTOjVnYfBPC0wZw20tw:1593209746265&q=site:events.linuxfoundation.org+community+days&spell=1&sa=X&ved=2ahUKEwjM8-nnwKDqAhXOUhUIHcMQBeIQBSgAegQIARAm&biw=1440&bih=789). So added the code to turn those pages off on the frontend.

**Comment by cjyabraham** [comment]
- Fix grey screen when closing mobile menu, ref #540

There's still something weird going on with the mobile menu.  Sometimes the page contents gets pushed down below the mobile menu, sometimes the mobile menu covers it.  See [this vid](https://drive.google.com/file/d/1c_Lzk-L7F7h0t79Wc4McOaofmZCTha6m/view?usp=sharing).  Interestingly, I can't reproduce this on a real mobile device so maybe it's fine.

- Added additional spacing to profile photos on mobile/tablet - Issue example - https://take.ms/djqLJ

I think what you did here looks fine but it now is inconsistent with the desktop view which uses a similar format of having the photo flush with the side of the box:
Screen Shot 2020-06-28 at 9 33 28 AM

If you fix it for mobile, should you do the same for desktop?  I personally don't favor one design over the other.

- Center align countdown on all devices - Issue example - https://take.ms/iI2dm

Looks good, thx.

- Make text centred inside buttons on mobile, add push effect on active - Issue example - https://take.ms/o9FiX

Your fix looks good.  Note that these Stackable buttons are "deprecated".  From now on Megan should be using the built in Buttons block or our new Buttons with Expiry block.  

- Use smaller images in front page slider - reduces page load by 200kb

To my eyes, the images now look significantly more blurry compared to the live site.  I think the extra 200kb is worth it.  Can you revert this (or use a larger thumbnail)?

- Dequeued some styles and scripts on front page only

Sounds good.  Thanks.

- Move slider script into app.js instead of inline, defer jquery front page only

What does "deferring jquery" do again?  Cause it to get processed later?

- Some small accessibility stuff

Thanks.

**Comment by thetwopct** [comment]
1) This is also an issue on the current site, so may not be related to the grey issue. The issue is related to the way the menu container reacts with the rest of the page - i.e. on front page, menu goes over content; on event page - e.g. embedded linux conference - it moves whole page down. I can fix if you think the inconsistency is a big issue but I don't see it harming UX as it is. I find it quite rare for mobile menus to allow interaction with the page while being open.

2) I don't have an issue with the cut-off edge being inconsistent, as it depends on what you regards as being consistent or not. I'm looking at the space above the image on mobile, and the way its flush to the top of that section. It looks bad in my opinion, and this modification solves it. Both versions retain a straight-edge cut-off. Example of issue:

20200629174846-IMG_8005 PNG

5) My eyes only see one image that is blurry - the "[welcome](https://lfeventsci.lndo.site/wp-content/uploads/2019/09/welcome-1024x491.jpg)" image. And this is the one we need to get rid of due to duplication. Were you able to work out how to edit these slides to fix that? I've changed the thumbnail the slider uses to a bigger version, although it only affects this one image (the rest are naturally small - approx 700px - anyway).

7) Deferring just means it's not [render blocking](https://web.dev/render-blocking-resources/), so the page gets on with loading and showing content, then loads jQuery / Scripts. As jQuery is only needed for the slider (which is on a delay) and for menus/filters that require user interaction, it seemed safe to defer it's loading.

**Comment by cjyabraham** [comment]
1. sounds fine as is

2. sounds good

5. they all looked blurry to me but the change you just made fixes that.  I've asked Megan which "Welcome" image to keep or if she wanted both.

**Comment by cjyabraham** [comment]
This is deployed.

**Pull request merged**
