### PR TITLE
Team page

### PR DESCRIPTION
**Pull request by cjyabraham**
[Related issue](https://github.com/LF-Engineering/lfevents/issues/670)

[Team page](https://pr-671-lfeventsci.pantheonsite.io/about/team/)

Comments from meeting with Megan:
- circles are good for the photos
- she doesn't love the grey box around each person
- she needs to be able to insert or delete a person in the middle of the list and keep them ordered
- it may look good to put a large group box around the whole listing to make them stand out from the white background
- needs to be launched by EOY
- team should be listed in alpha order by first name; TBD if Angela should be listed first

### CODE REVIEW

**Comment by cjyabraham** [comment]
I created a CPT for staff members and a shortcode for output.  What's left is just to make it look good.  We need confirmation as to whether Angela should go first.

**Comment by thetwopct** [comment]
- I added a generic avatar image upload option to the LFEvents Options page so if a member doesn't have a photo it will display something.
- Added a little bit of interactivity when hovering over members - image pops a little, and name underlines. Not sure about the pop effect as it seems a little glitchy sometimes, but let me know what you think.
- Not quite sure about the grey background color, it could be slightly lighter?
- Would be good to get real names and job titles in there so can experiment and make sure column widths accommodate those properly

**Comment by cjyabraham** [comment]
A few comments:
- I think we should go 4 on each row since there are going to be a lot (>30)
- I'd prefer no animation... I don't think it serves us in any way and is a bit distracting... it also makes it seem like you might be able to click when you can't.
- ya, I'm not sure what the grey background is doing... maybe remove it?

**Comment by thetwopct** [comment]
- Kept the grey background for now but changed shade slightly and I think I like it now. Also needs some contrast for the default avatar. Lets leave it like this until we get feedback.
- Removed the image animation
- 4 per row on desktop
- Made name slightly smaller as with 4 members per row the names looked too close together

**Comment by cjyabraham** [comment]
I think a slight tweak is needed on mobile: since there is no hover state you don't need room for the animated line and can move the title closer to the name.  Perhaps we can wait for Megan's feedback before this kind of fine-tuning...

**Pull request merged**
