### PR TITLE
Additional Fixes (WP 5.6)

### PR DESCRIPTION
**Pull request by thetwopct**
- Fixes https://github.com/LF-Engineering/lfevents/issues/619 on mobile
- Fixes https://github.com/LF-Engineering/lfevents/issues/602 so table cells can now be seen, also syncs styling frontend and backend - [demo and testing](https://pr-623-lfeventsci.pantheonsite.io/dpdk-summit-apac/contact-us/) 
- New font stack regarding Linux/CN stack issue

### CODE REVIEW

**Comment by thetwopct** [comment]
Sorry for all the commit history I branched from the old WP56 branch instead of from master before pulling down latest 🐸 Nothing major here, but my intention was we could keep this open for a couple of days for Megans comments on WP56, but we can always do that when/if its needed 🙏

**Comment by cjyabraham** [comment]
I think there are some problems with the changes you made to the pricing block here.  [Here's yours](https://pr-623-lfeventsci.pantheonsite.io/kubecon-cloudnativecon-north-america/register/) and [here's the live one](https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/register/):
- I prefer the larger font for prices on desktop widths as it is on the live site
- mobile width seems to have lost its internal padding on the table cells; the text now is right at the edge.  It looks especially weird on tablet-width screens.  I prefer it with some padding.... maybe half-way between yours and the live site?
- on mobile width I think I prefer the larger prices... it's just the word "Complimentary" is too big.  Maybe the size needs to be half-way between your version and the live one?

As for tables:
- when I insert a table, it appears to have a grey border in the editor, but then on the front-end it doesn't.  I think what I had in mind for #602 was very faint lines, like you use for spacers or group blocks, just to allow the editor to see where the cells are.  I think the grey border is another way to go but it needs to default that way on the front-end to be consistent.

**Comment by thetwopct** [comment]
1) OK
2) Fixed. I think I was working on a test event and the background colours of the table weren't being applied, wondered why it looked so weird!
3) Needs some balancing - the system doesn't differentiate between a price and a long word. The Kubecon example has nice short dates for the timing period, but if you insert ones that go cross months or years, the date cell is very wide, and this impacts on the width the price/complimentary text has to be in.

Current:
2020-12-21-123250@2x

My changes:
2020-12-21-123316@2x

I know which works for me. But let me know.

4) The Kubecon example has the embedded font size CSS in the page. I've now integrated that in to the block / improved it so it works better on all devices / for 2-4 columns, so in future I would hope the editors don't need to add any custom CSS regardless of layout/content. 

5) Have switched to using an outline style around each cell with a dashed edge, a bit hacky the way it has to be done, but thats the table styles we're working with.

2020-12-21-125946@2x

**Comment by cjyabraham** [comment]
All looks good with the pricing block, just a couple comments about the table:
- the table I added at the bottom of [this page](https://pr-623-lfeventsci.pantheonsite.io/wp/wp-admin/post.php?post=89942&action=edit) doesn't have a clear dotted line.  Sometimes it's dotted, sometimes it's solid, sometimes there's a double-line.  Is this a result of the weird table styles you've inherited?
Screen Shot 2020-12-22 at 12 21 54 PM
- when I add a header or footer to the table they appear with borders, the header borders lighter than the footer; could you make the border style consistent with the rest of the table (i.e. none)?

**Comment by thetwopct** [comment]
- Tried to fix the dotted line issue, should be better
- Header and footer should now follow same style as body of table
- Had to remove styles applied to control the very wide logos image used on Kubecon as this was affecting the handlebar resizer on images

Following on from that last issue - currently, any image can be set to more than the content width, and it will push out the sidebar / content of the editor. i.e. here is a large JPG being told to be 1500px wide:

2020-12-22-233719@2x

When you insert a large image, WordPress inserts it in to the available max-width space of the container. It requires manual changing of the width dimension to push it out of the container. However, SVGs don't seem to follow this pattern, and insert at larger sizes than the container, hence the Kubecon logo issue.

Solutions as I see them:
1) Find a way to limit the max size of image dimensions in Image Block (doesnt seem to be an option currently, may be possible with JS)
2) Ask Safe SVG to make SVGs respect max-width on insert
3) Ask Editors to manually update the width dimension of big SVGs when inserting to 1150/1200px
4) Just put up with it until 2) or 1) is fixed in core

**Comment by cjyabraham** [comment]
When I insert a table with 8 cells, the editor will scroll left-right to accommodate.  It's weird that this scroll doesn't appear as well for SVGs that are too wide.

**Pull request merged**
