### PR TITLE
WP 5.6 upgrade

### PR DESCRIPTION
**Pull request by cjyabraham**
Problems in the editor:
- [ ] 1) [Kubecon editor display](https://pr-617-lfeventsci.pantheonsite.io/wp/wp-admin/post.php?post=817&action=edit) stretches more than full-screen so that you can't properly access the right sidebar; the reason appears to be that the long line of project SVG logos is pushing out the width of the editor.  If you make them smaller the right sidebar returns to normal.  
- [ ] 2) Buttons with expiry aren't respecting the align center setting and always seem to align things left; see [Kubecon](https://pr-617-lfeventsci.pantheonsite.io/wp/wp-admin/post.php?post=817&action=edit)
- [ ] 3) When I select a Group in the editor it appears to put a selected blue rectangle around an element above it
- [ ] 4) Groups with the Event Gradient style don't show the correct padding; when you click them, they change shape unexpectedly
- [ ] 5) Spacer block outline often includes content below it; [see here](https://pr-617-lfeventsci.pantheonsite.io/wp/wp-admin/post.php?post=19267&action=edit)

Problems on front-end:
- [ ] 7) Cover blocks appear to be a bit taller than they used to be; they appear to have a bit of extra padding at the top and bottom; I'm not sure if we need to fix this

- [ ] 8) Maybe you can fix [this issue](https://github.com/LF-Engineering/lfevents/issues/618) at the same time.
- [ ] 9) Also, we should turn off block patterns like we have done for LFPH and CNCF?

Each time we upgrade Gutenberg we seem to be running into issues like the above.  Is there a root cause?  Our use of Foundation?  Perhaps we should try to make things more compliant with the Gutenberg way to avoid ongoing issues like this?

### CODE REVIEW

**Comment by thetwopct** [comment]
There are numerous causes, but primarily is that Gutenberg is ever-evolving. Block markup has been changed in the editor, or styles updated in core. We could detach from the core styles, but that would have its own update issues and wouldn't prevent markup changes as Gutenberg evolves.

I don't think Foundation helps, or some of the early styling decisions, but we either live with that and implement workarounds, or we spend the time to fix the tech debt. Some of these editor problems are forcing me to deal with some of those decisions anyway.

- I've turned off block patterns for now
- Added a fix for the section headers and added context in the issue
- Spacer block updated
- Cover block has had 1rem padding added to core styles. I presume this is to stop content butting up to the edges - which we use spacers for. I would recommend keeping the core padding, and adjusting our spacers. Currently they are set 120px, but 100px (responsive) readjusts. 80px (responsive) may look slightly better. Seems like most of the cover blocks I checked aren't using responsive spacers anyway, so they need to be updated. [New](https://pr-617-lfeventsci.pantheonsite.io/open-source-summit-japan/), [Old](https://events.linuxfoundation.org/open-source-summit-japan/).

More to come, lots to do.

**Comment by thetwopct** [comment]
Additional issues

- [ ] I'm noticing the editor is much slower than previous - loading the Kubecon NA page grinds my computer to a halt. Need to investigate what's happening.

- [ ] jQuery migrate is now being loaded - https://cln.sh/clAV2h - some recent changes around that, I've not read in to it, maybe you want to 

- [ ] Seeing console message "Block successfully updated for `core/column`" warnings - https://cln.sh/cVNgjd - don't understand why.

**Comment by cjyabraham** [comment]
With your additional issues: 

1. I don't experience the slowness you're describing.  It seems roughly the same for me as the live site.  Could it be all those twitter embeds slowing you down?

2. It appears that jquery migrate is loading on the live site as well.  The one difference may be the version, going from 1.4.1 to 3.3.2.

3. It only seems to do that once.  After you save it it won't do it again.  I guess the block might have changed the markup format or something?

In general, I agree with your feeling about moving off of foundation.  Do you think we can do this in an iterative fashion or do we need a clean break?  

I also think we should stay on core styles and try to keep as close to Gutenberg as we can as it evolves so that we can benefit from all the updates.

**Comment by thetwopct** [comment]
1. Maybe its my Lando, I will rebuild. The Kubecon version is very slow for me, but also working on other pages, like landing pages where there is virtually no content, seems slow to me too. Debug/Query Monitor isn't picking anything up. 

2. We've been [dequeuing jquery.migrate](https://github.com/LF-Engineering/lfevents/blob/8544262e01e88aca0838ce06f4c9512b24f099b9/web/wp-content/themes/lfevents/library/enqueue-scripts.php#L55) so if its loading on production that's not right. We shouldn't need it as our jQuery is already the latest and everything works.

3. Lets see how this editor fixing goes and go from there. 

- [ ] Should we also take this opportunity to upgrade to PHP 7.4? In `pantheon.yml` seems we're pegged at 7.3

**Comment by cjyabraham** [comment]
2. the jQuery core version is now the one we are already running on the front-end

Good call.  I have upgraded php to 7.4 for this branch, cncf and lfph.

**Comment by thetwopct** [comment]
OK, I think this is ready for review. I've refactored a lot of CSS and the editor CSS was nuked and rewritten. 

1) I think is fixed, but there a few issues here. The image is inserted at approx 1230px width and this width is applied as an inline style. I think as the image is a SVG, and the Safe SVG plugin doesn't always displaying images accurately this doesnt make that oversized width obvious. The image itself is not a strict SVG and fails SVG autocross as it includes PNG files. The SVG is around 250kb, so for the size it displays, I would recommend switching it to a PNG. For it to look nicer on mobile I'd also recommend 2 rows of icons instead of 1 very long row.

2) Fixed. Also added a border around the buttons in the editor to help see the block.

3) Fixed. 

4) Let me know if this is fixed for you. I can't properly reproduce it post editing the editor.scss file. The group block moves for me when focused, but this is the block inserter being inserted, this seems to be a core styling change.

5) Fixed

7) Once live, we need to review the spacers used inside the cover block and make sure they have responsive Styles attached to them.

12) I'm still seeing the console messages about `core/columns` regardless of how many times the page is saved. Bit weird. But gonna assume its a core problem right now.

Closes https://github.com/LF-Engineering/lfevents/issues/615 You said "Both should have rounded corners by default." but I presume you mean both should have that _Style option_ by default, as its not the default style for either currently. Have added a constrained style for Groups and its content.
Demo of group cover https://pr-617-lfeventsci.pantheonsite.io/open-compliance-summit/

Closes https://github.com/LF-Engineering/lfevents/issues/612 

Worked on https://github.com/LF-Engineering/lfevents/issues/619 so the editor styles look better. On the front end, there is some weirdness of your example around 1000px with the "Complimentary" wording being too big / not centered. Do you have a specific idea of how that should look?

**Comment by cjyabraham** [comment]
a. I've made a note to ask Megan about replacing this long row of project icons with two rows and using a PNG.  We'd likely need Alex to design that for us.

b. For #619, I think the "Complimentary" wording should ideally look similar to how it does [on the live site with the inline style adjustment](https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/register/).  I think taking down the font further, however, won't look good for the prices.  Maybe just leave as you have it for now.  If they decide they want to use an inline style again for this it's not the end of the world.

c. The prices and "Complimentary" on the mobile width, however, look too big.  Should we bring those down in size?

d. Why doesn't [the cover here](https://pr-617-lfeventsci.pantheonsite.io/kubecon-cloudnativecon-north-america/sponsor/#sponsorship-benefits) have rounded corners even though I selected the "Border" style?

e. Why can't I see the "Button Group" outline on the buttons on [this page](https://pr-617-lfeventsci.pantheonsite.io/wp/wp-admin/post.php?post=1216&action=edit)?

**Comment by thetwopct** [comment]
b. I've tidied the block a bit more as I spotted another issue around 1000px. Should be good now.

c. Cover fixed

d. Should be fixed

**Comment by cjyabraham** [comment]
It's highly weird that [the word expired](https://pr-617-lfeventsci.pantheonsite.io/kubecon-cloudnativecon-north-america/register/) jumps from above the price to below the price when you reduce the browser width.  Not a problem though, just funny.

**Pull request merged**
