### PR TITLE
HubSpot

### PR DESCRIPTION
**Pull request by cjyabraham**
Examples of inline newsletter form and footer newsletter form on [this page](https://pr-635-lfeventsci.pantheonsite.io/kubecon-cloudnativecon-europe/).

### CODE REVIEW

**Review by thetwopct — APPROVED** [review]
OK good.

For home page:
- I tidied up some of the PHP as it was referencing unused variables (like hashtag and wechat, if we add those we can add them back in)
- I have left a TODO in footer.php as the non-event pages are using "event-footer" styling, which is a bit confusing. When we update the non-event footer to match the new LF style guide we can diverge these styles and rename etc.

For event footer:
- I've accounted for when the text color changes in the event settings, with the form submit, errors and confirmation messages now adopting the selected color.

General hubspot:
- I added some padding to the privacy text under the form so it aligns a little better on mobile 
- Have added a slight background color (transparency) to the submit button on hover. This seems to work in my testing with either white/black text and various color backgrounds.
- Some refactoring to be done later once SFMC forms are completely gone, lets loop back to that.

Random:
- Fixed a couple of old code sniffs that were in the mu-plugin

**Comment by cjyabraham** [comment]
Some remaining loose ends:
- [ ] back out homepage hub footer; Craig wants us to wait on his footer design before we move ahead with that
- [ ] My mouse cursor is a pointer on the [mid-page submit button but a hand on the footer submit button](https://pr-635-lfeventsci.pantheonsite.io/kubecon-cloudnativecon-europe/); probably they should both be a hand

**Comment by cjyabraham** [comment]
I discussed the homepage hub footer with @ccr and we have these comments:
- Could you remove the max-width on the opening line of text so that it doesn't line break unless it runs out of space
- Craig would like that we copy the general idea behind the field styles we use on the cncf footer, so use just an underline for the fields without the full white box
- Craig is investigating whether we can consolidated all the fine-print text so we don't need to so much of it in multiple places
- The placement of the social icons are fine except could you please copy hover style that you see on the [lf site](https://www.linuxfoundation.org/) footer?  Different colors are used to match the brand of the social site.

**Comment by thetwopct** [comment]
4. I copied that style first, then removed it. The style doesn't really work when left aligned - either the icons need indenting to account for the circular background, or on hover the background circle doesn't align with the left line and goes outside it. I can quickly recreate it to show you the issue if you want; but if it worked I would have made it work.

**Comment by thetwopct** [comment]
1. Done
2. Copied across
3. Will await updates. There isn't much overlap in the newsletter text and footer text.
5. The Submit button on the form I've changed to just "Subscribe". Using all caps text isn't inline with other LF buttons, and I'm not really sure an exclamation mark is warranted for a simple subscribe form action? Exclamation marks in copy are a bit amateurish.
6. Does reCaptcha work for LF Asia? The current privacy recaptcha text in footer displays on both sites, but I felt that as it was a Google product chances of it working in China would be remote?

Also toyed with moving social icons to be the last item, the heavy white of them kinda works to balance the copyright text IMO:

**Comment by thetwopct** [comment]
- Made copyright text a slightly darker grey against the blue to let focus stay on mailing list and social icons. [Still accessible](https://webaim.org/resources/contrastchecker/?fcolor=C4C4C4&bcolor=003366) 👍 
- Moved social icons below copyright as I feel like the balance works.
- Added the overlay background to the social icons with the "brand" colors for each. The twitter (1st child) rollover looks strange as it pushes out the left alignment sight line.
- Made the social icons smaller inline with other LF sites
- Footer on event pages now retains current grey styling to avoid color clashes

**Pull request merged**
