### PR TITLE
Social Block plugin

### PR DESCRIPTION
**Pull request by thetwopct**
**Social Block plugin**
When inserted the block looks for the Social meta for an event and displays corresponding social icons. 

- It's hooked in to the colour meta of each event, so user can easily select colour of icons that match the rest of the page, or pick generic colours (black / white).
- I've added a hover effect that adds a slight hue to any colour of icon.
- It has alignment so can be put on left/right/center of page easily.
- I added the CSS in to the theme rather the block.
- I added meta setup for instagram link in to the social event sidebar, but haven't implemented the icon in to the footer yet (will do that as part of footer redesign)
- I've purposely left out any additional text inside the block, I felt that any prompt or advertising hashtags for events could be done using standard blocks around the social icons?

Additional:
I felt the size of the icons could be a variable, so if this is useful I can get it done.

### CODE REVIEW

**Comment by cjyabraham** [comment]
This looks great!  I've been playing around with it to [try and add a title and put it in a box](https://pr-523-lfeventsci.pantheonsite.io/kubernetes-forum-delhi/) and managed to make it look half-decent nested inside Columns->Stackable Container.  Maybe we should come up with a few other decent examples of how it can be used before we show the others?

**Comment by thetwopct** [comment]
Yes great, I didn't think of styles like that, looks good. As we're looking to move away from Stackable, I think it would be useful to have this as a complete block, so adding an editable text area is probably a good idea?

To do:

- Add editable text area
- Add padding / background style / border-radius around icons
- Add size adjustment to icons

I'll work on it today

**Comment by dankohn** [comment]
Can you please also support the WeChat functionality from cncf.io of popping a QR code?

**Comment by thetwopct** [comment]
@dankohn It's implemented the same - so if the QR image is present in the event, the icon will display. If clicked the QR image displays in pop-up, same as footer.

**Comment by thetwopct** [comment]
@dankohn I've set up a quick example for you to test https://pr-523-lfeventsci.pantheonsite.io/open-source-summit-north-america/

**Comment by cjyabraham** [comment]
@thetwopct the one [on the right here](https://pr-523-lfeventsci.pantheonsite.io/kubernetes-forum-delhi/) uses the Gutenberg Group block.  Instead of creating one all-in-one block we could style the Group block to have rounded corners.  I'd like to do that anyway so that Megan can start using the Group block instead of the Stackable Container.  In WP 5.4 I think the Group block will also have gradients etc.  So maybe we want to make this a re-usable block or a block pattern rather than an all-in-one block?

I suggest, as a first step, we talk with Megan and Kristin to see if we're going in the right direction in terms of style and see how much flexibility they might want.  Then we can consider options?

**Comment by thetwopct** [comment]
@dankohn I've fixed styling on the WeChat pop-up. I'm not super happy with it, as it covers the logo, but placing it further above means it then covers the text above it, so neither solution is ideal for me. I've switched the activation of the pop-up to a click, as hover (as in the footer) was being activated as I scrolled through the page. 

@cjyabraham 

I've added a variable icon size, think this makes it look much better and gives a bit more control.

I've added two new Block Styles for the Group block.

- Rounded corners with some slight padding
- Rounded corners with some slight padding + auto centered and controlled width

The Group block is 100% width by default, so it needs to be put in to a column like you did in your example to get some control. The second Style is an attempt to deal with that, but this affects the alignment control. 

If we had the text in the Social Block instead of group we can handle all that better, but for now I think its OK and we can get some feedback.

There is a problem with using different sizing if the Social Block is used twice on the same page (not including social footer block) but I see that as an outlier case so I haven't found a solution to that. 

https://pr-523-lfeventsci.pantheonsite.io/open-source-summit-north-america/

**Pull request closed without merging**
