### PR TITLE
Hero work

### PR DESCRIPTION
**Pull request by thetwopct**
- Rejigged all templates, separated out the hero from the entry content on non-event pages, consistent edge padding
- Revised hero as a gradient color inline with the Style Guide
- New home hero in line with Style Guide
- Updated 404 page to fit inside template
- Basic search page styling (search restricted to events)
- Basic archive styling
- Disabled tags

### Changes made on the database:
- Homepage - H2 to H1 tag + remove bold, convert 2nd text to paragraph, add featured image
- Rename Uncategorized post category to News
- LF Asia Homepage - remove spacers around H4 if present, add featured image

### Still to do:
- Test on LF Asia
- iFrame embed / iFrame sort out on news post that embeds newsletter (not responsive)

### CODE REVIEW

**Comment by cjyabraham** [comment]
Some comments:
1. - [ ] the bottom padding is looking to be too large now [at the bottom of pages](https://pr-613-lfeventsci.pantheonsite.io/about/contact/); did that get increased again?
2. - [ ] I think "past events" should remain a button as I almost didn't see the link there

**Comment by thetwopct** [comment]
- Padding reduced 
- Past/upcoming events changed to button as per style guide, added to template
- Community events template updated
- Fixed date in loop
- LF Asia hero updated

I've added the new home hero image to LF Asia, but don't love it. I like it slightly more with an increased font size of the first line of text. I wonder if Cheryls image would work there too?

**Comment by cjyabraham** [comment]
Something is going on with the width of events on mobile.  Go [here](https://pr-613-lfeventsci.pantheonsite.io/automotive-linux-summit/) with width 360px and you get a grey bar at the side:
Screen Shot 2020-12-03 at 6 05 00 PM

It doesn't do that on the live site

**Comment by cjyabraham** [comment]
See if you can find a better way to display this button on mobile:
Screen Shot 2020-12-03 at 5 59 00 PM

**Comment by cjyabraham** [comment]
[This commit](https://github.com/LF-Engineering/lfevents/pull/613/commits/87896fd43d2b90d3f8f3402f8f30aafb04687648) is a weird layout issue when I'm logged in:
Screen Shot 2020-12-03 at 10 31 31 PM

**Comment by cjyabraham** [comment]
Craig has asked for the subpage headers to be 400px high.

**Pull request merged**
