### PR TITLE
Speakers block improvements

### LINKED ISSUE #667: Speakers block gradient style and other issues
1. WRT [adding the gradient style to the Speakers block](https://github.com/LF-Engineering/lfevents/commit/0a3a8679a0a2ee8ff045df1c3462662f07538a78), I'm finding it works differently to the event gradient style on the Group block.  When you select the style on the Group block, it shows the event gradient on the front-end no matter what, even if colors are selected for the text and background.  When you select the style on the Speakers block, you need to first deselect any Color 1 and Color 2 settings in order for the event gradient to show.  I think these should both work the same way: if the style is selected then the color settings are ignored.

2. What is the difference between the "Plain" style and the "Gradient" style?  They both seem to look more or less the same on the front-end.  Both have a color gradient.  Is there a way to differentiate these better or just eliminate one?

3. I can't seem to ever get white text on the front-end, even when the option is set.  [This used to work](https://events.linuxfoundation.org/kubernetes-ai-day-north-america/program/program-committee/).

----

I think we basically need two styles:
- “Event Gradient”
- “Custom Colors” which applies the custom set colors.  When only one color is set it doesn’t make a gradient.  When two are set it does.

Both styles should honor the white/black text setting.

### PR DESCRIPTION
**Pull request by thetwopct**
Deals with issues and closes #667

### CODE REVIEW

**Comment by cjyabraham** [comment]
This currently seems to break existing blocks.  See: https://pr-668-lfeventsci.pantheonsite.io/open-networking-edge-summit-north-america/ 
Screen Shot 2021-09-14 at 1 23 05 PM

**Comment by cjyabraham** [comment]
1. Existing blocks seem to have both their background and text color changed.  See the one on [this page](https://pr-668-lfeventsci.pantheonsite.io/open-networking-edge-summit-north-america/) compared with the [live version](https://events.linuxfoundation.org/open-networking-edge-summit-north-america/).  Is this avoidable?  If not, we can do some kind of migration.

2. I don't seem to be able to click on a speaker to expand their profile.

**Comment by thetwopct** [comment]
1. I think I've done the logic so existing block should now be fine. I checked a few other events they now seem to match. 
2. Code sniffs added a space, should be fixed now.

**Comment by cjyabraham** [comment]
Two minor things:
1. In the Color Options "Select option" is a possible value.  I think there should just be the other two values and it should default to Event Gradient.  I'm not sure if this complicates the migration for the old blocks.
1. I don't think we need "Chose background colors" and "Chose text color" help text on the form, however, if we do include them I think it should be "Choose..." and not "Chose...".

Neither of the above are blockers so I'll deploy.

**Comment by thetwopct** [comment]
1. Is for backwards compatibility. Couldn’t really be done any other way. If gradient was default, it would be selected on block load and then that would overwrite existing options. 
2. I can change in future. The sidebar was doing some weird layout stuff and that stopped it. 
3. Wasn’t by design or intentional, must be where event gradient class is applied to the block. I can make it more consistent in future or can leave as is. The way we do the gradient with custom colours is tricky to inject in to the editor so I purposefully wanted to avoid styling the editor block.

**Pull request merged**
