### PR TITLE
Upgrade to WP 6.4.1

### PR DESCRIPTION
**Pull request by cjyabraham**
Issue #848
[Dev instance](https://pr-849-lfeventsci.pantheonsite.io/)
Also includes update to the default privacy notice on newsletter forms, as per #841

### CODE REVIEW

**Comment by cjyabraham** [comment]
I checked through the front-end and did not find any render differences from the live site.

The editor in the back-end has some minor increase in spacing between paragraphs. It's strange since the CNCF site [had a collapsing of space between paragraphs](https://github.com/cncf/cncf.io/pull/810#issuecomment-1805564512). In this case, I don't think anything necessarily needs to be done to fix things.

@thetwopct assigning to you to do your checks or approve the PR.

**Comment by thetwopct** [comment]
This is still marked as a draft PR. Is it ready for review?

**Comment by cjyabraham** [comment]
yes

**Comment by thetwopct** [comment]
I can't see any issues

**Comment by cjyabraham** [comment]
On deployment, we should enable the bulk edit option for Nested Pages to the following roles:
Screenshot 2023-11-19 at 5 52 30 PM

**Comment by cjyabraham** [comment]
Pricing blocks need migrating by hand once deployed to live

**Pull request merged**
